### ISSUE TITLE
no multithreading?

### ISSUE THREAD

**Issue by spieiga** [suaefar/ryzen-test#1]
I'm a Ryzen linux user and wanted to try and reproduce what you are seeing with segfaults.

However, I noticed in buildloop.sh, you are using make -j 1

I'm surprised this is happening with only one thread, most reported the errors when using make -j 16 (for ryzens with 8 cores)

**Comment by suaefar** [comment]
This is because 1x "make -j 16" leads to lower load than 16x "make -j 1".
If "nproc" returns 16 on your machine the buildloop.sh script will be started 16 times.
