### ISSUE TITLE
zram mount error

### ISSUE THREAD

**Issue by keantoken** [suaefar/ryzen-test#11]
Using the latest GIT version I get this in the terminal:

$ ./kill-ryzen.sh
Install required packages
[sudo] password for keantoken: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.3).
0 upgraded, 0 newly installed, 0 to remove and 23 not upgraded.
Create compressed ramdisk
64G
mount: wrong fs type, bad option, bad superblock on /dev/zram0,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

```
~$ inxi -bxx
System:    Host: ronin Kernel: 4.12.0-10.1-liquorix-amd64 x86_64 bits: 64 gcc: 6.4.0
           Desktop: Xfce 4.12.3 (Gtk 2.24.31) dm: lightdm Distro: Debian GNU/Linux buster/sid
Machine:   Device: desktop Mobo: ASUSTeK model: ROG STRIX B350-F GAMING v: Rev X.0x
           UEFI [Legacy]: American Megatrends v: 0809 date: 08/01/2017
CPU:       Quad core AMD Ryzen 5 1500X (-HT-MCP-) arch: Zen rev.1 speed: 3500 MHz (max)
Graphics:  Card: NVIDIA GK208 [GeForce GT 730] bus-ID: 26:00.0 chip-ID: 10de:1287
           Display Server: x11 (X.Org 1.19.3 ) driver: nvidia Resolution: 1280x960@60.00hz
           OpenGL: renderer: GeForce GT 730/PCIe/SSE2 version: 4.5.0 NVIDIA 375.82 Direct Render: Yes
Network:   Card: Intel I211 Gigabit Network Connection
           driver: igb v: 5.4.0-k port: e000 bus-ID: 1e:00.0 chip-ID: 8086:1539
Drives:    HDD Total Size: 370.1GB (49.8% used)
Info:      Processes: 355 Uptime: 9 min Memory: 2932.9/7985.5MB
           Init: systemd v: 234 runlevel: 5 default: 2 Gcc sys: 7.2.0 alt: 4.4/4.6/4.8/4.9/5/6
           Client: Shell (bash 4.4.121 running in xfce4-terminal) inxi: 2.3.34 
```

**Comment by keantoken** [comment]
Linux 4.13-rc5 works fine, so perhaps it is a problem with Liquorix.

**Comment by suaefar** [comment]
Okay, so can I close this issue?

**Comment by keantoken** [comment]
I would at least like to know why the problem occurred, entering the kill-ryzen script manually into the terminal didn't reveal anything and I didn't see anything in dmesg to indicate what the problem is.

Linux 4.12-rc7 also works, so almost certainly a Liquorix specific thing.

**Comment by suaefar** [comment]
Which interpreter do you use?
Maybe something with bash (version)?
I don't think its specific to the code.
We only "support" stock Ubuntu 17.04, therefore I will close this issue.

**Comment by keantoken** [comment]
Bash 4.4-5. I am using Debian Sid.

My guess would be Liquorix has changed Zram settings or virtual filesystem settings or something in such a way that the script fails.

**Comment by damentz** [comment]
Looking at the kill-ryzen.sh script, the mounting error occurs because we're mounting a ram disk with "discard" option.  Discard isn't supported on devices that don't support ATA_TRIM, e.g., ram disks.

Why Ubuntu's kernel allows you to mount _ram disks_ with discard is a mystery in itself.  Perhaps the discard option itself is ignored silently for compatibility reasons?
