### ISSUE TITLE
the script couldn't run on arch linux

### ISSUE THREAD

**Issue by Syh15198462** [suaefar/ryzen-test#14]
the script is has based on ubuntu? when i run it on arch linux ,it has to show some errors on terminal.

**Comment by 2b145** [comment]
you need to remove the build-essentials from the script..arch uses the base-devel package.

**Comment by Syh15198462** [comment]
@2b145 thanks a lot, I havd decided to take RMA to change a CPU

**Comment by 2b145** [comment]
what kernel version are you using? gcc 7.2? I had segv faults within 1 minute on ubuntu 17.04 but arch(kernel 4.13.3-2 , gcc (GCC) 7.2.0) I have had non. Have you tried raising soc voltage to 1.1v and using default values for vcore and ram? RMA would obviously be the best course of action but AMD will make you try the following first :) The above worked for me.
