### ISSUE TITLE
Add other package manager

### ISSUE THREAD

**Issue by b2ag** [suaefar/ryzen-test#2]
Hi, I'm using Arch Linux and there is no apt-get. For Arch users it should be "sudo pacman base-devel".
Maybe do something like:
```
if PKGMGR="$( which apt-get 2>/dev/null )"; then sudo "$PKGMGR" build-essential; fi
if PKGMGR="$( which pacman 2>/dev/null )"; then sudo "$PKGMGR" base-devel; fi
...
```

**Comment by suaefar** [comment]
Hi,
thank you for your suggestion.

I'm not too familiar with non-debian based distributions and dont want to invest the time.
The test can always be run from an Ubuntu live system.
I would accept a corresponding pull request of course.

**Comment by n3ziniuka5** [comment]
I am also running arch, I simply commented out `sudo apt install build-essential || exit 1` and everything worked for me.

**Comment by b2ag** [comment]
I created #4 to give an example how to integrate the two lines I posted.

**Comment by suaefar** [comment]
I'm sorry, but the implementation throws an error on Ubuntu.
I had to revert the merged changes.
If you want this to be merged, please provide a patch that was tested on both platforms.

**Comment by b2ag** [comment]
I'm sorry! Such few lines and I still got it wrong. I forgot the "install" parameter for apt-get. Frankly, I also forgot the "-S" for Arch's pacman. I created a new pull request in #5 which I have verified to work with Ubuntu 16.04.3 LTS running inside a Docker container.
