### ISSUE TITLE
Will this bug can be fixed by gcc update or kernel patch？

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [suaefar/ryzen-test#21]
Can this bug be fixed by gcc update？
It‘s too trouble to RMA my ryzen cpu.

**Comment by suaefar** [comment]
Short answer: We don't know, but probably not.

AMD has been silent for over half a year.
Hardly any official information is available.
For the time being, RMA is the only solution to get a reliable system.

**Comment by suaefar** [comment]
@ZhengshuaiPENG Please ask AMD and tell us if you got any information on that.

**Comment by ZhengshuaiPENG** [comment]
@suaefar I contacted AMD and I am waiting for their response. I will update this when I got some information about that.

**Comment by ZhengshuaiPENG** [comment]
@suaefar I just explained the situation to AMD, they just return me back a replacement CPU which produced in 33 week. Test in ubuntu 17.04
I have 16G G-Skill 3200 C14 RAM, still get build failed , but I haven't seen any segment in output. 
Also tried kill-ryzen 4 4, but also failed

**Comment by ZhengshuaiPENG** [comment]
checked with log file, seems that the errors occurs due to code level or some thing like this (Error: dereferencing pointer to incomplete type...)  and no segfault in logs. So that's means this new CPU should be non faulty?

**Comment by suaefar** [comment]
The script wont work with Ubuntu 17.10 due to a known bug/incompatibility. You can try to replace the gcc version of 7.1 with 7.2 in the souce code. However, it is not clear if this combination triggers the segfaults.

**Comment by Oxalin** [comment]
As I previously stated elsewhere: I was able to trigger the segfault (on a faulty CPU) with GCC 7.2 on ArchLinux. @ZhengshuaiPENG The error you are seeing is mostly caused by a known incompatibility between GCC 7.1 and glib 2.26 (see my comment in issue #6 )

**Comment by ZhengshuaiPENG** [comment]
@Oxalin My new CPU batch number is  1733SUS, it seems that the most part of segfault RMA CPU is the same batch number as mine. So I suppose this cpu should be fine. And as I can't enter into 17.04 live system, I won't test it in Ubuntu. But I have Arch installed in my system, so could u tell me how to test this script on Arch? thanks

**Comment by suaefar** [comment]
Remember that this script does not calculate anything deterministic. It is likely to trigger a hardware bug under certain conditions (Ubuntu 17.04!)
With Arch it might, or not, have this property.
To be sure you will need to find someone confirming that it triggers the bug with the same software configuration, which under Arch is subject to change every minute (rolling disto).
