### ISSUE TITLE
Memory runs out before tests finishes

### ISSUE THREAD

**Issue by MycroftHolmes1989** [suaefar/ryzen-test#30]
I only have 16GB of RAM. Will the test serve its purpose if I create a 16GB Ramdisk instead of 64GB? Or mount an empty partition and use the partition for the test?

**Comment by m-r-s** [comment]
You don't need to create the ramdisk, the script does it.
The size is only the maximum uncompressed size.
The problem occurs, when the compressed size exceeds the available space in memory.
You can reduce the number of independent compilation processes and increase the number of threads per process [1].

[1] https://github.com/suaefar/ryzen-test#requirements

**Comment by MycroftHolmes1989** [comment]
That was exactly what I was looking for. Thanks.
