### ISSUE TITLE
Could we get a script for cleaning up afterwards? (or at least instructions)

### ISSUE THREAD

**Issue by dralley** [suaefar/ryzen-test#7]
For instance, getting rid of the ramdisk, freeing up the disk space, etc.

**Comment by dralley** [comment]
Thanks for the project, unfortunately my CPU is affected : /

**Comment by BuzzBumbleBee** [comment]
If you run in ramdisk mode the following should be all that's needed

1. Kill all processes started by the script (`ps aux` can help here)

2. Unmount and rmmod the zram module
```
sudo umount /mnt/ramdisk
sudo rmmod zram
```

**Comment by suaefar** [comment]
Just reboot and the ramdisk with all its contents will disappear.
Nothing should be written outside the ramdisk apart from installing the build-essential package.
You can remove it with "sudo apt purge build-essential".

**Comment by Nuc1eoN** [comment]
> Just reboot and the ramdisk with all its contents will disappear.

How do I reboot the RAM disk?

**Comment by Oxalin** [comment]
@Nuc1eoN: He means to reboot your system. The RAM and its content (including the RAMdisk) will be cleared.

**Comment by m-r-s** [comment]
That's right! Just power down or reboot your system.

**Comment by Nuc1eoN** [comment]
Yeah but I'm testing on a live CD, so rebooting takes a long time. Is there no faster way? I get some error message about the ram disk when trying to run a seocnd time.

**Comment by Oxalin** [comment]
@Nuc1eoN : I had (have) a patch for that in a fork. However, my branch uses GCC 7.2.0 instead of 7.1.0, because 7.1.0 is broken against many newer Linux distributions that are using glib 2.26 or newer. You could use my branch, but change GCC's version back to 7.1.0. You can find the code here: https://github.com/Oxalin/ryzen-test/commits/master

**Comment by Nuc1eoN** [comment]
@Oxalin thanks great work! :)
My main system is a fully updated Archlinux. Will your script work there without issues?

**Comment by Oxalin** [comment]
@Nuc1eoN : last I checked, it was working fine. That's how I tested my faulty CPU a few months ago. If you encounter a problem, let me know under my fork.
